"""Benchmark and biological validation for :mod:`mir.biomarkers.kmer_stats`.

Downloads HLA-A*02 GILGFVFTL-specific TRB CDR3 sequences from VDJdb
(via ``tests/assets/fetch_vdjdb_gilgfvftl.sh``) and compares them against
1 000 random TRB CDR3 sequences generated by OLGA.

The GILGFVFTL epitope (Influenza A matrix protein M1_58-66) is presented by
HLA-A*02 and is one of the best-characterised CD8+ T-cell epitopes.  Public
TCR beta chains recognising this epitope are dominated by TRBV19 usage and a
conserved **"RS"** motif in the CDR3 loop.  We expect k-mers containing "RS"
to be significantly enriched compared to the OLGA background.

Run with ``pytest -s tests/test_kmer_stats.py`` to see benchmark output.

Requires:
    * ``tests/assets/gilgfvftl_trb_cdr3.txt.gz`` — run
      ``bash tests/assets/fetch_vdjdb_gilgfvftl.sh`` first.
"""

from __future__ import annotations

import gzip
import os
import time
import unittest
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from tests.conftest import skip_integration
from mir.biomarkers.kmer_stats import (
    KmerCounter,
    compare_kmer_counts,
    compare_repertoire_kmers,
)
from mir.common.clonotype import ClonotypeAA
from mir.common.repertoire import Repertoire

ASSETS = Path(__file__).parent / "assets"
GILG_FILE = ASSETS / "gilgfvftl_trb_cdr3.txt.gz"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_gilgfvftl_cdr3s() -> list[str]:
    """Load GILGFVFTL-specific CDR3 sequences from the asset file."""
    if not GILG_FILE.exists():
        raise FileNotFoundError(
            f"{GILG_FILE} not found.  Run:\n"
            "  bash tests/assets/fetch_vdjdb_gilgfvftl.sh"
        )

    with gzip.open(GILG_FILE, "rt", encoding="utf-8") as f:
        seqs = [l.strip() for l in f if l.strip()]

    if len(seqs) < 20:
        raise RuntimeError(f"Expected >= 20 GILGFVFTL CDR3s, got {len(seqs)}")
    return seqs


def _make_repertoire(cdr3s: list[str]) -> Repertoire:
    """Build a minimal Repertoire from a list of CDR3aa strings."""
    clonotypes = [ClonotypeAA(cdr3aa=s) for s in cdr3s]
    return Repertoire(clonotypes)


def _generate_olga_background(n: int = 1000, seed: int = 42) -> list[str]:
    """Generate *n* random TRB CDR3aa sequences using OLGA."""
    from mir.basic.pgen import OlgaModel

    np.random.seed(seed)
    model = OlgaModel(chain="TRB")
    return model.generate_sequences(n)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@unittest.skipUnless(GILG_FILE.exists(),
                     "VDJdb asset missing — run tests/assets/fetch_vdjdb_gilgfvftl.sh")
@skip_integration
@pytest.mark.integration
class TestKmerStatsBenchmark(unittest.TestCase):
    """K-mer differential analysis: GILGFVFTL-specific vs OLGA background."""

    @classmethod
    def setUpClass(cls):
        cls.gilg_cdr3s = _load_gilgfvftl_cdr3s()
        cls.bg_cdr3s = _generate_olga_background(1000)
        cls.gilg_rep = _make_repertoire(cls.gilg_cdr3s)
        cls.bg_rep = _make_repertoire(cls.bg_cdr3s)

    # -- counting benchmarks -----------------------------------------------

    def test_kmer_counter_speed(self):
        """Benchmark KmerCounter on both repertoires."""
        for label, rep in [("GILGFVFTL", self.gilg_rep),
                           ("OLGA bg  ", self.bg_rep)]:
            t0 = time.perf_counter()
            kc = KmerCounter(k=3, repertoire=rep)
            _ = kc.counts()
            elapsed = time.perf_counter() - t0
            n_kmers = len(kc.counts())
            n_clones = len(rep.clonotypes)
            print(f"\n  {label}: {n_clones} clonotypes → "
                  f"{n_kmers} unique 3-mers in {elapsed*1000:.1f} ms")

    # -- comparison benchmarks ---------------------------------------------

    def test_compare_repertoire_speed(self):
        """Benchmark end-to-end repertoire comparison."""
        for k in (2, 3, 4):
            t0 = time.perf_counter()
            df = compare_repertoire_kmers(self.gilg_rep, self.bg_rep, k=k)
            elapsed = time.perf_counter() - t0
            n_sig = (df["p_val_adj"] < 0.05).sum()
            print(f"\n  k={k}: {len(df)} kmers, {n_sig} significant "
                  f"(adj p < 0.05) in {elapsed*1000:.1f} ms")

    # -- biological validation: RS motif -----------------------------------

    def test_rs_motif_enriched_k3(self):
        """k=3 RS-containing k-mers should be among the top enriched."""
        df = compare_repertoire_kmers(self.gilg_rep, self.bg_rep, k=3)
        # Keep only k-mers enriched in GILGFVFTL (freq_fc > 1)
        enriched = df[df["freq_fc"] > 1].sort_values("p_val")

        top20 = enriched.head(20)
        rs_in_top20 = [kmer for kmer in top20.index if "RS" in kmer]

        print(f"\n  Top 20 enriched 3-mers (GILGFVFTL vs OLGA):")
        print(f"  {'k-mer':<8} {'FC':>8} {'p_val':>12} {'p_adj':>12} {'RS?':>4}")
        print(f"  {'-'*8} {'-'*8} {'-'*12} {'-'*12} {'-'*4}")
        for kmer in top20.index:
            row = top20.loc[kmer]
            tag = " *" if "RS" in kmer else ""
            print(f"  {kmer:<8} {row['freq_fc']:>8.2f} "
                  f"{row['p_val']:>12.2e} {row['p_val_adj']:>12.2e}{tag}")

        self.assertGreater(len(rs_in_top20), 0,
                           "Expected RS-containing k-mers in top 20 enriched")

    def test_rs_motif_enriched_k4(self):
        """k=4 RS-containing k-mers should be among the top enriched."""
        df = compare_repertoire_kmers(self.gilg_rep, self.bg_rep, k=4)
        enriched = df[df["freq_fc"] > 1].sort_values("p_val")

        top30 = enriched.head(30)
        rs_in_top30 = [kmer for kmer in top30.index if "RS" in kmer]

        print(f"\n  Top 30 enriched 4-mers (GILGFVFTL vs OLGA):")
        print(f"  {'k-mer':<8} {'FC':>8} {'p_val':>12} {'p_adj':>12} {'RS?':>4}")
        print(f"  {'-'*8} {'-'*8} {'-'*12} {'-'*12} {'-'*4}")
        for kmer in top30.index:
            row = top30.loc[kmer]
            tag = " *" if "RS" in kmer else ""
            print(f"  {kmer:<8} {row['freq_fc']:>8.2f} "
                  f"{row['p_val']:>12.2e} {row['p_val_adj']:>12.2e}{tag}")

        self.assertGreater(len(rs_in_top30), 0,
                           "Expected RS-containing k-mers in top 30 enriched")

    def test_rs_pvalue_significant(self):
        """At least one RS-containing k-mer should have adjusted p < 0.05."""
        df = compare_repertoire_kmers(self.gilg_rep, self.bg_rep, k=3)
        rs_kmers = df[[("RS" in kmer) for kmer in df.index]]
        # Filter for enriched in GILGFVFTL
        rs_enriched = rs_kmers[rs_kmers["freq_fc"] > 1]

        print(f"\n  All RS-containing 3-mers:")
        for kmer in rs_enriched.sort_values("p_val").index:
            row = rs_enriched.loc[kmer]
            sig = "***" if row["p_val_adj"] < 0.001 else (
                  "**" if row["p_val_adj"] < 0.01 else (
                  "*" if row["p_val_adj"] < 0.05 else ""))
            print(f"    {kmer}  FC={row['freq_fc']:.2f}  "
                  f"p={row['p_val']:.2e}  p_adj={row['p_val_adj']:.2e} {sig}")

        min_padj = rs_enriched["p_val_adj"].min()
        self.assertLess(min_padj, 0.05,
                        f"Best RS k-mer adj p-value = {min_padj:.2e}, expected < 0.05")

    # -- summary -----------------------------------------------------------

    def test_benchmark_summary(self):
        """Print combined summary of GILGFVFTL vs OLGA comparison."""
        print(f"\n  Dataset sizes:")
        print(f"    GILGFVFTL CDR3s : {len(self.gilg_cdr3s)}")
        print(f"    OLGA background : {len(self.bg_cdr3s)}")

        for k in (2, 3, 4, 5):
            df = compare_repertoire_kmers(self.gilg_rep, self.bg_rep, k=k)
            enriched = df[df["freq_fc"] > 1].sort_values("p_val")
            n_sig = (enriched["p_val_adj"] < 0.05).sum()
            top3 = list(enriched.head(3).index)
            rs_any = any("RS" in km for km in enriched.head(20).index)
            print(f"    k={k}: {len(df):>5} kmers, "
                  f"{n_sig:>3} significant, "
                  f"top3={top3}, "
                  f"RS in top20={'yes' if rs_any else 'no'}")


if __name__ == "__main__":
    unittest.main()
