"""TCRNET-like neighborhood enrichment for clonotype repertoires.

TCRNET enrichment is a **purely MC-control** algorithm: it counts Hamming-1
(or Levenshtein-1) neighbors of each query sequence in a provided control
repertoire (real or synthetic) and tests whether the query's own neighborhood
is more densely populated than expected from that background.  No OLGA Pgen is
computed at any stage.

For each query clonotype:

- *n* = neighbors in sample (same clonotype + Hamming/Levenshtein matches, optionally V/J restricted)
- *N* = total possible neighbors in sample (satisfying gene constraints)
- *m* = neighbors in control
- *M* = total possible neighbors in control

Statistical tests:

- ``pvalue_mode="binomial"`` — ``P(X ≥ n)`` where ``X ~ Binomial(N, m/M)``
- ``pvalue_mode="beta-binomial"`` — ``P(X ≥ n)`` where ``X ~ BetaBinomial(N, α, M-m+1)``
  with ``α = (m+pc)*q_factor``; q_factor scales the alpha (effective successes) identically to
  how it scales the binomial probability numerator
  (recommended when control is noisy or sample size is small)

Control options
---------------
* **Real control** (recommended default) — a separate donor or pooled baseline
  repertoire.  Real controls automatically capture V/J gene usage and sequence
  length biases, so ``normalize_control_vj_usage`` is usually not needed.
* **Synthetic control** — generated by :class:`~mir.basic.pgen.McPgenPool` or
  :class:`~mir.basic.pgen.OlgaModel`.  Synthetic sequences are drawn from the
  OLGA *recombination* model (pre-thymic selection), so their neighborhood
  density is lower than a real post-selection repertoire by a factor of
  roughly Q ≈ 3–5 for human TRB.  Pass ``q_factor=Q`` to correct for this
  bias; the corrected control density ``Q × m/M`` is used for the enrichment
  test while raw counts are preserved in metadata.

Neighbor-depleted sequences
----------------------------
Swapping the roles of sample and control detects **neighbor-depleted** sequences
— clonotypes that are *less* dense in the sample than in the control.  This can
reveal sequences that are selectively lost (e.g. anergic clones, deleted
specificities) relative to a healthy baseline::

    result = compute_tcrnet(
        control_repertoire,          # control becomes the "sample" query
        control=sample_repertoire,   # sample becomes the "control" background
        match_mode="vj",
        pvalue_mode="beta-binomial",
    )

Sequences with low ``p_value`` are those for which the control has significantly
more neighbors than the sample — i.e. sample-depleted clones.

ALICE as a special case of TCRNET
-----------------------------------
The ALICE Poisson model and the TCRNET binomial model converge in the limit of
a large synthetic pool:

    ALICE (Poisson, λ = N × pgen_1mm)  ≅
    TCRNET (Binomial, p = m/M with M ≫ n, m ≫ 1)

With a large synthetic control TCRNET is equivalent to ALICE **without** the
theoretical Pgen fallback and **without** Q-scaling of the background.  One can
still use the raw neighbor counts and cluster sizes from such a run, but the
statistical test should account for thymic selection.  The recommended
formulation is ``pvalue_mode="beta-binomial"`` with an effective control size of
``M / Q`` (or equivalently ``q_factor=Q``)::

    compute_tcrnet(
        rep,
        control=large_synthetic_locus_rep,   # e.g. 100M OLGA sequences
        match_mode="vj",
        pvalue_mode="beta-binomial",
        q_factor=3.0,   # thymic-selection correction; divides effective M by Q
    )

To reproduce the original ALICE paper using TCRNET::

    compute_tcrnet(
        rep,
        control=McPgenPool.build_synthetic(100_000_000, locus="TRB").as_locus_repertoire(),
        match_mode="vj",
        pvalue_mode="beta-binomial",
        q_factor=3.0,
    )

This implementation is metadata-first:
- neighborhood counts and p-values are written directly into clonotype metadata,
- table output is optional and derived from the annotated repertoire.

This module is a highly customized MIR implementation inspired by ideas
described in the TCRNET framework paper, not a literal line-by-line
reimplementation of the original software.

References
----------
Pogorelyy MV, Shugay M. A Framework for Annotation of Antigen Specificities in
High-Throughput T-Cell Repertoire Sequencing Studies. Front Immunol.
2019;10:2159.  doi:10.3389/fimmu.2019.02159. PMID:31616409.

Pogorelyy MV *et al.* Detecting T cell receptors involved in immune responses
from single repertoire snapshots. PLoS Biol. 2019;17(6):e3000314.
doi:10.1371/journal.pbio.3000314. PMID:31194732.
"""

from __future__ import annotations

from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from math import ceil
import math
import multiprocessing
import os
import typing as t

_MP_CTX = multiprocessing.get_context("spawn")
from dataclasses import dataclass

import polars as pl
from scipy.stats import betabinom, binom

from mir.basic.gene_usage import GeneUsage
from mir.biomarkers._shared import (
    MatchMode,
    apply_bh_qvalues_to_metadata,
    iter_loci,
    lookup_gene_frac,
    match_flags,
    normalize_match_mode,
)
from mir.common.clonotype import Clonotype
from mir.common.alleles import allele_to_major
from mir.common.control import ControlManager
from mir.common.metaclonotype import (
    MetaClonotypeClustering,
    metaclonotypes_from_seed_neighbors,
)
from mir.common.repertoire import LocusRepertoire, SampleRepertoire
from mir.common.sampling import resample_to_gene_usage
from mir.graph.neighborhood_enrichment import compute_neighborhood_stats_by_locus

PValueMode = t.Literal["binomial", "beta-binomial"]
_PVALUE_PARALLEL_MIN_CLONOTYPES = 20_000


def _resolve_n_jobs(n_jobs: int) -> int:
    if n_jobs == -1:
        try:
            import psutil
            n = psutil.cpu_count(logical=False)
            if n:
                return n
        except Exception:
            pass
        return os.cpu_count() or 1
    return max(1, int(n_jobs))


@dataclass(frozen=True)
class TcrnetParams:
    """TCRNET parameter bundle.

    When ``q_factor > 1.0`` the control density is multiplied by ``q_factor``
    before the enrichment test.  This corrects for the fact that synthetic
    (OLGA) controls are drawn from the recombination model *before* thymic
    selection, so their neighborhood density is systematically lower than a
    post-selection repertoire by a factor of roughly Q ≈ 3–5 for human TRB.
    Estimate Q as ``median(pgen_real / pgen_olga)`` for sequences with at least
    one real-control match (see :meth:`~mir.basic.pgen.McPgenPool.build_real`).
    Leave at the default of ``1.0`` when using a real control.
    """

    metric: t.Literal["hamming", "levenshtein"] = "hamming"
    threshold: int = 1
    match_mode: MatchMode = "none"
    pvalue_mode: PValueMode = "binomial"
    min_neighbors: int = 2
    q_factor: float = 1.0

    def validate(self) -> None:
        if self.metric not in {"hamming", "levenshtein"}:
            raise ValueError("metric must be 'hamming' or 'levenshtein'")
        if self.threshold < 0 or self.threshold > 1:
            raise ValueError("threshold must be in [0, 1] for TCRNET")
        if self.match_mode not in {"none", "v", "j", "vj"}:
            raise ValueError("match_mode must be one of: none, v, j, vj")
        if self.pvalue_mode not in {"binomial", "beta-binomial"}:
            raise ValueError("pvalue_mode must be 'binomial' or 'beta-binomial'")
        if self.min_neighbors < 0:
            raise ValueError("min_neighbors must be >= 0")
        if self.q_factor <= 0:
            raise ValueError("q_factor must be > 0")


@dataclass(frozen=True)
class TcrnetResult:
    """In-memory TCRNET output."""

    table: pl.DataFrame
    params: TcrnetParams

def _empty_locus(locus: str) -> LocusRepertoire:
    return LocusRepertoire(clonotypes=[], locus=locus)


def _df_to_locus_repertoire(df: pl.DataFrame, locus: str) -> LocusRepertoire:
    rows: list[Clonotype] = []
    for idx, rec in enumerate(df.to_dicts()):
        rows.append(
            Clonotype(
                sequence_id=str(idx),
                locus=locus,
                duplicate_count=max(1, int(rec.get("duplicate_count", 1) or 1)),
                junction=str(rec.get("junction", "")),
                junction_aa=str(rec.get("junction_aa", "")),
                v_gene=allele_to_major(str(rec.get("v_gene", ""))),
                j_gene=allele_to_major(str(rec.get("j_gene", ""))),
                _validate=False,
            )
        )
    return LocusRepertoire(clonotypes=rows, locus=locus)


def _resolve_control_loci(
    *,
    target_loci: dict[str, LocusRepertoire],
    control: LocusRepertoire | SampleRepertoire | None,
    control_type: str | None,
    species: str,
    control_manager: ControlManager | None,
    control_kwargs: dict | None,
) -> dict[str, LocusRepertoire]:
    if control is not None:
        control_loci = iter_loci(control)
        out: dict[str, LocusRepertoire] = {}
        for locus in target_loci:
            out[locus] = control_loci.get(locus, _empty_locus(locus))
        return out

    if control_type is None:
        raise ValueError("Provide either control repertoire or control_type")

    mgr = control_manager or ControlManager()
    kwargs = dict(control_kwargs or {})

    out: dict[str, LocusRepertoire] = {}
    for locus in target_loci:
        rec_df = mgr.ensure_and_load_control_df(control_type, species, locus, **kwargs)
        out[locus] = _df_to_locus_repertoire(rec_df, locus=locus)
    return out


def _normalize_control_vj(
    *,
    target_locus: LocusRepertoire,
    control_locus: LocusRepertoire,
    random_seed: int | None,
) -> LocusRepertoire:
    if not control_locus.clonotypes:
        return control_locus

    gu = GeneUsage.from_repertoire(target_locus)
    target_vj = gu.vj_usage(target_locus.locus, count="duplicates")
    if not target_vj:
        return control_locus

    return t.cast(
        LocusRepertoire,
        resample_to_gene_usage(
            control_locus,
            target_vj,
            scope="vj",
            weighted=True,
            random_seed=random_seed,
        ),
    )


def _p_value(n: int, N: int, m: float, M: float, mode: PValueMode) -> float:
    if N <= 0:
        return 1.0
    if M <= 0:
        return 1.0

    if mode == "binomial":
        p = min(1.0, max(0.0, m / M))
        return float(binom.sf(n - 1, N, p))

    # Degenerate: q-adjusted alpha ≥ M means effective background density ≥ 1 (miscalibration).
    if m >= M:
        return 1.0
    alpha = float(m + 1)
    beta = float((M - m) + 1)
    return float(betabinom.sf(n - 1, N, alpha, beta))


def _fold_enrichment(n: int, N: int, m: float, M: float) -> float:
    if N <= 0 or M <= 0:
        return 0.0
    if m <= 0:
        return math.inf if n > 0 else 0.0
    return float((n / N) * (M / m))


def _compute_tcrnet_metrics_batch(
    clonotypes: list[Clonotype],
    *,
    locus_self: dict[str, dict[str, int]],
    locus_ctrl: dict[str, dict[str, int]],
    pvalue_mode: PValueMode,
    pseudocount: float = 1.0,
    min_neighbors: int = 0,
    q_factor: float = 1.0,
    match_mode: str = "none",
    gene_usage_fracs: "dict | None" = None,
    m_background_total: int = 0,
) -> list[tuple[str, int, int, int, float, float, float, float, float]]:
    """Compute TCRNET metrics per clonotype.

    ``neighbor_count`` includes the sequence itself (self is always a
    distance-0 match), so ``min_neighbors=2`` means self + at least one
    additional neighbour within the edit-distance threshold.  Clonotypes with
    ``neighbor_count < min_neighbors`` receive ``p_value = 1.0`` without any
    statistical computation.

    ``q_factor`` scales the effective number of control successes: ``alpha =
    (m + pc) * q_factor``.  For the binomial this is equivalent to scaling the
    null probability numerator; for the beta-binomial it scales the alpha shape
    parameter identically.  Use ``q_factor > 1`` to correct synthetic controls
    for thymic selection.  Raw counts ``m`` and ``M`` are stored in metadata
    without pseudocount or q-scaling; pseudocount and q_factor are applied only
    inside the statistical computation.

    When ``match_mode != "none"`` and ``gene_usage_fracs`` is provided, *M* is
    replaced by ``P_ctrl(gene) × m_background_total`` so the denominator uses
    control gene-usage frequencies rather than the raw filtered count.
    """
    out: list[tuple[str, int, int, int, float, float, float, float, float]] = []
    use_gene_scaling = (
        match_mode != "none"
        and gene_usage_fracs is not None
        and m_background_total > 0
    )
    for clonotype in clonotypes:
        sid = clonotype.sequence_id
        s_stat = locus_self.get(sid, {"neighbor_count": 0, "potential_neighbors": 0})
        n = int(s_stat["neighbor_count"])
        N = int(s_stat["potential_neighbors"])
        c_stat = locus_ctrl.get(sid, {"neighbor_count": 0, "potential_neighbors": 0})
        m_count = int(c_stat["neighbor_count"])  # true raw count, stored in metadata as-is
        m_stat = (m_count + pseudocount) * q_factor  # alpha: q scales effective successes for both modes
        if use_gene_scaling:
            p_gene = lookup_gene_frac(
                match_mode, clonotype.v_gene or "", clonotype.j_gene or "",
                gene_usage_fracs,
            )
            M_val: float = p_gene * m_background_total
        else:
            M_val = float(int(c_stat["potential_neighbors"]))
        M_stat = M_val + pseudocount
        if n < min_neighbors:
            out.append((sid, n, N, m_count, M_val, 1.0, 0.0,
                        float(n / N) if N > 0 else 0.0,
                        float(m_stat / M_stat) if M_stat > 0 else 0.0))
            continue
        p = _p_value(n, N, m_stat, M_stat, pvalue_mode)
        fe = _fold_enrichment(n, N, m_stat, M_stat)
        sample_density = float(n / N) if N > 0 else 0.0
        control_density = float(m_stat / M_stat) if M_stat > 0 else 0.0
        out.append((sid, n, N, m_count, M_val, p, fe, sample_density, control_density))
    return out


def _compute_tcrnet_metrics_batch_from_args(
    args: tuple,
) -> list[tuple[str, int, int, int, float, float, float, float, float]]:
    """Pickle-friendly wrapper for process-pool batch execution."""
    (clonotypes, locus_self, locus_ctrl, pvalue_mode, pseudocount, min_neighbors, q_factor,
     match_mode, gene_usage_fracs, m_background_total) = args
    return _compute_tcrnet_metrics_batch(
        clonotypes,
        locus_self=locus_self,
        locus_ctrl=locus_ctrl,
        pvalue_mode=pvalue_mode,
        pseudocount=pseudocount,
        min_neighbors=min_neighbors,
        q_factor=q_factor,
        match_mode=match_mode,
        gene_usage_fracs=gene_usage_fracs,
        m_background_total=m_background_total,
    )


_TCRNET_TABLE_SCHEMA: dict[str, type] = {
    "sequence_id": pl.Utf8,
    "locus": pl.Utf8,
    "junction_aa": pl.Utf8,
    "v_gene": pl.Utf8,
    "j_gene": pl.Utf8,
    "n_neighbors": pl.Int64,
    "N_possible": pl.Int64,
    "m_control_neighbors": pl.Float64,
    "M_control_possible": pl.Float64,
    "sample_density": pl.Float64,
    "control_density": pl.Float64,
    "fold_enrichment": pl.Float64,
    "p_value": pl.Float64,
    "q_value": pl.Float64,
}


def tcrnet_table(
    repertoire: LocusRepertoire | SampleRepertoire,
    *,
    metadata_prefix: str = "tcrnet",
    sort: bool = True,
) -> pl.DataFrame:
    """Build a TCRNET result table from clonotype metadata."""
    rows: list[dict[str, t.Any]] = []
    for locus, lrep in iter_loci(repertoire).items():
        for clonotype in lrep.clonotypes:
            md = clonotype.clone_metadata
            n = int(md.get(f"{metadata_prefix}_n", 0))
            N = int(md.get(f"{metadata_prefix}_N", 0))
            m = int(md.get(f"{metadata_prefix}_m", 0))
            M = int(md.get(f"{metadata_prefix}_M", 0))
            rows.append(
                {
                    "sequence_id": clonotype.sequence_id,
                    "locus": locus,
                    "junction_aa": clonotype.junction_aa,
                    "v_gene": clonotype.v_gene,
                    "j_gene": clonotype.j_gene,
                    "n_neighbors": n,
                    "N_possible": N,
                    "m_control_neighbors": float(m),
                    "M_control_possible": float(M),
                    "sample_density": float(n / N) if N > 0 else 0.0,
                    "control_density": float(md.get(f"{metadata_prefix}_control_density", float(m / M) if M > 0 else 0.0)),
                    "fold_enrichment": float(md.get(f"{metadata_prefix}_fold", 0.0)),
                    "p_value": float(md.get(f"{metadata_prefix}_p_value", 1.0)),
                    "q_value": float(md.get(f"{metadata_prefix}_q_value", 1.0)),
                }
            )
    if not rows:
        return pl.DataFrame(schema=_TCRNET_TABLE_SCHEMA)
    table = pl.from_dicts(rows)
    if sort:
        table = table.sort(["p_value", "fold_enrichment"], descending=[False, True])
    return table


def compute_tcrnet(
    repertoire: LocusRepertoire | SampleRepertoire,
    *,
    control: LocusRepertoire | SampleRepertoire | None = None,
    control_type: str | None = None,
    species: str = "human",
    control_manager: ControlManager | None = None,
    control_kwargs: dict | None = None,
    normalize_control_vj_usage: bool = False,
    metric: t.Literal["hamming", "levenshtein"] = "hamming",
    threshold: int = 1,
    match_mode: str = "none",
    pvalue_mode: PValueMode = "binomial",
    pseudocount: float = 1.0,
    q_factor: float = 1.0,
    random_seed: int | None = None,
    metadata_prefix: str = "tcrnet",
    as_table: bool = True,
    min_neighbors: int = 2,
    n_jobs: int = -1,
) -> TcrnetResult | LocusRepertoire | SampleRepertoire:
    """Compute TCRNET-like enrichment, write clonotype metadata, and optionally return a table.

    TCRNET is a **purely MC-control** enrichment test: it counts Hamming/Levenshtein
    neighbors in a control repertoire (real or synthetic) and tests whether the
    sample neighborhood density exceeds the control background.  No OLGA Pgen is
    computed at any stage.

    Either pass an explicit control repertoire (``control=...``) or request a
    managed control via ``control_type`` with :class:`ControlManager`.

    Args:
        min_neighbors: Minimum ``neighbor_count`` (self + additional neighbours
            within the edit-distance threshold) a clonotype must have before
            the statistical test is computed.  ``neighbor_count`` always includes
            the sequence itself, so the default of 2 means *self plus at least
            one additional neighbour* — the minimum size for an enrichment test.
            Clonotypes below this threshold receive ``p_value = 1.0`` without
            any computation.
        q_factor: Selection correction for synthetic controls (default ``1.0``,
            i.e. no correction).  Multiply the control density by this factor
            before the enrichment test: ``p_ctrl_adj = q_factor × m / M``.
            When using an OLGA synthetic control, sequences are drawn from the
            recombination model (pre-thymic selection) so their neighborhood
            density is lower than a post-selection repertoire by a factor of
            roughly Q ≈ 3–5 for human TRB.  Estimate Q as
            ``median(pgen_real / pgen_olga)`` for sequences with at least one
            real-control match.  Raw ``m`` and ``M`` counts are always stored
            in clonotype metadata unchanged; only the enrichment test and
            ``control_density`` use the adjusted value.  Leave at ``1.0`` when
            using a real control.
    """
    norm_match_mode = normalize_match_mode(match_mode)
    params = TcrnetParams(
        metric=metric,
        threshold=threshold,
        match_mode=norm_match_mode,
        pvalue_mode=pvalue_mode,
        min_neighbors=min_neighbors,
        q_factor=q_factor,
    )
    params.validate()
    n_jobs = _resolve_n_jobs(n_jobs)
    match_v, match_j = match_flags(norm_match_mode)

    query_loci = iter_loci(repertoire)
    control_loci = _resolve_control_loci(
        target_loci=query_loci,
        control=control,
        control_type=control_type,
        species=species,
        control_manager=control_manager,
        control_kwargs=control_kwargs,
    )
    for locus, qrep in query_loci.items():
        crep = control_loci.get(locus, _empty_locus(locus))
        if normalize_control_vj_usage:
            crep = _normalize_control_vj(
                target_locus=qrep,
                control_locus=crep,
                random_seed=random_seed,
            )

        self_stats = compute_neighborhood_stats_by_locus(
            qrep,
            background=None,
            metric=metric,
            threshold=threshold,
            match_v_gene=match_v,
            match_j_gene=match_j,
            add_background_pseudocount=False,
            n_jobs=n_jobs,
        )
        control_stats = compute_neighborhood_stats_by_locus(
            qrep,
            background=crep,
            metric=metric,
            threshold=threshold,
            match_v_gene=match_v,
            match_j_gene=match_j,
            add_background_pseudocount=False,
            n_jobs=n_jobs,
        )

        locus_self = self_stats.get(locus, {})
        locus_ctrl = control_stats.get(locus, {})

        # Gene-usage conditioning: replace raw V/J-filtered M with
        # P_ctrl(gene) × M_total for a smoothed, frequency-based denominator.
        ctrl_gene_fracs: dict | None = None
        m_background_total = 0
        if match_v or match_j:
            ctrl_gu = GeneUsage.from_repertoire(crep)
            ctrl_gene_fracs = {
                "v": ctrl_gu.v_fraction(locus),
                "j": ctrl_gu.j_fraction(locus),
                "vj": ctrl_gu.vj_fraction(locus),
            }
            m_background_total = len(crep.clonotypes)

        metrics_by_sid: dict[str, tuple[int, int, int, int, float, float, float, float]] = {}
        executor_mode = os.getenv("MIRPY_TCRNET_PVALUE_EXECUTOR", "process").strip().lower()
        should_parallelize_pvalues = (
            n_jobs > 1 and (
                len(qrep.clonotypes) >= _PVALUE_PARALLEL_MIN_CLONOTYPES
                or executor_mode == "thread"
            )
        )
        if should_parallelize_pvalues:
            batch_size = max(1, ceil(len(qrep.clonotypes) / n_jobs))
            batches = [
                qrep.clonotypes[start : start + batch_size]
                for start in range(0, len(qrep.clonotypes), batch_size)
            ]
            batch_args = [
                (batch, locus_self, locus_ctrl, pvalue_mode, pseudocount, min_neighbors, q_factor,
                 norm_match_mode, ctrl_gene_fracs, m_background_total)
                for batch in batches
            ]
            if executor_mode == "thread":
                with ThreadPoolExecutor(max_workers=n_jobs) as executor:
                    metric_chunks = list(executor.map(_compute_tcrnet_metrics_batch_from_args, batch_args))
            else:
                with ProcessPoolExecutor(max_workers=n_jobs, mp_context=_MP_CTX) as executor:
                    metric_chunks = list(executor.map(_compute_tcrnet_metrics_batch_from_args, batch_args))

            for chunk in metric_chunks:
                for sid, n, N, m, M, p, fe, sample_density, control_density in chunk:
                    metrics_by_sid[sid] = (n, N, m, M, p, fe, sample_density, control_density)
        else:
            for sid, n, N, m, M, p, fe, sample_density, control_density in _compute_tcrnet_metrics_batch(
                qrep.clonotypes,
                locus_self=locus_self,
                locus_ctrl=locus_ctrl,
                pvalue_mode=pvalue_mode,
                pseudocount=pseudocount,
                min_neighbors=min_neighbors,
                q_factor=q_factor,
                match_mode=norm_match_mode,
                gene_usage_fracs=ctrl_gene_fracs,
                m_background_total=m_background_total,
            ):
                metrics_by_sid[sid] = (n, N, m, M, p, fe, sample_density, control_density)

        for clonotype in qrep.clonotypes:
            sid = clonotype.sequence_id
            n, N, m, M, p, fe, sample_density, control_density = metrics_by_sid[sid]
            clonotype.clone_metadata[f"{metadata_prefix}_n"] = n
            clonotype.clone_metadata[f"{metadata_prefix}_N"] = N
            clonotype.clone_metadata[f"{metadata_prefix}_m"] = m
            clonotype.clone_metadata[f"{metadata_prefix}_M"] = M
            clonotype.clone_metadata[f"{metadata_prefix}_sample_density"] = sample_density
            clonotype.clone_metadata[f"{metadata_prefix}_control_density"] = control_density
            clonotype.clone_metadata[f"{metadata_prefix}_fold"] = fe
            clonotype.clone_metadata[f"{metadata_prefix}_p_value"] = p

    apply_bh_qvalues_to_metadata(repertoire, metadata_prefix=metadata_prefix)

    if as_table:
        return TcrnetResult(table=tcrnet_table(repertoire, metadata_prefix=metadata_prefix), params=params)
    return repertoire


def add_tcrnet_metadata(
    repertoire: LocusRepertoire | SampleRepertoire,
    *,
    control: LocusRepertoire | SampleRepertoire | None = None,
    control_type: str | None = None,
    species: str = "human",
    control_manager: ControlManager | None = None,
    control_kwargs: dict | None = None,
    normalize_control_vj_usage: bool = False,
    metric: t.Literal["hamming", "levenshtein"] = "hamming",
    threshold: int = 1,
    match_mode: str = "none",
    pvalue_mode: PValueMode = "binomial",
    pseudocount: float = 1.0,
    q_factor: float = 1.0,
    random_seed: int | None = None,
    metadata_prefix: str = "tcrnet",
    min_neighbors: int = 2,
    n_jobs: int = -1,
) -> LocusRepertoire | SampleRepertoire:
    """Compute TCRNET stats and write them into clonotype metadata in-place."""
    return t.cast(
        LocusRepertoire | SampleRepertoire,
        compute_tcrnet(
            repertoire,
            control=control,
            control_type=control_type,
            species=species,
            control_manager=control_manager,
            control_kwargs=control_kwargs,
            normalize_control_vj_usage=normalize_control_vj_usage,
            metric=metric,
            threshold=threshold,
            match_mode=match_mode,
            pvalue_mode=pvalue_mode,
            pseudocount=pseudocount,
            q_factor=q_factor,
            random_seed=random_seed,
            metadata_prefix=metadata_prefix,
            min_neighbors=min_neighbors,
            as_table=False,
            n_jobs=n_jobs,
        )
    )


def metaclonotypes_from_tcrnet(
    repertoire: LocusRepertoire,
    *,
    metadata_prefix: str = "tcrnet",
    q_value_max: float = 0.05,
    metric: t.Literal["hamming", "levenshtein"] = "hamming",
    threshold: int = 1,
    match_mode: MatchMode = "vj",
) -> MetaClonotypeClustering:
    """Build metaclonotypes around TCRNET-significant clonotypes.

    One cluster is created per significant clonotype (representative), and
    members are all first-neighborhood clonotypes under the provided scope.
    """
    norm_match_mode = normalize_match_mode(match_mode)
    match_v, match_j = match_flags(norm_match_mode)

    seeds = [
        c.sequence_id
        for c in repertoire.clonotypes
        if float(c.clone_metadata.get(f"{metadata_prefix}_q_value", 1.0)) <= q_value_max
    ]
    return metaclonotypes_from_seed_neighbors(
        repertoire,
        seed_clonotype_ids=seeds,
        metric=metric,
        threshold=threshold,
        match_v_gene=match_v,
        match_j_gene=match_j,
        cluster_prefix="tcrnet_mc",
    )
